name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Lint code
        run: npm run lint

      - name: 🛠 Build project (Next.js 15)
        run: npm run build

      - name: ✅ Type check
        run: npx tsc --noEmit

      - name: 🧪 Placeholder Test
        run: echo "No tests defined yet" && exit 0
